In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import GridSearchCV
%matplotlib inline

In [ ]:
dataset = pd.read_csv('diamonds.csv')

In [ ]:
##dataset.replace(to_replace="Fair",value='0',inplace=True)
##dataset.replace(to_replace="Good",value='1',inplace=True)
##dataset.replace(to_replace="Ideal",value='2',inplace=True)
##dataset.replace(to_replace="Premium",value='3',inplace=True)
##dataset.replace(to_replace="Very Good",value='4',inplace=True)

In [ ]:
#datasetindeki string değerler int yapılır
#string to int
dataset.replace(to_replace="J",value='0',inplace=True)
dataset.replace(to_replace="I",value='1',inplace=True)
dataset.replace(to_replace="H",value='2',inplace=True)
dataset.replace(to_replace="G",value='3',inplace=True)
dataset.replace(to_replace="F",value='4',inplace=True)
dataset.replace(to_replace="E",value='5',inplace=True)
dataset.replace(to_replace="D",value='6',inplace=True)

In [ ]:
#datasetindeki string değerler int yapılır
#string to int
dataset.replace(to_replace="I1",value='0',inplace=True)
dataset.replace(to_replace="SI2",value='1',inplace=True)
dataset.replace(to_replace="SI1",value='2',inplace=True)
dataset.replace(to_replace="VS2",value='3',inplace=True)
dataset.replace(to_replace="VS1",value='4',inplace=True)
dataset.replace(to_replace="VVS2",value='5',inplace=True)
dataset.replace(to_replace="VVS1",value='6',inplace=True)
dataset.replace(to_replace="IF",value='7',inplace=True)

In [ ]:
#output and inputs are determins here
#giriş ve çıkış değerleri verilir
X = dataset.drop('cut', axis=1)
Y = dataset['cut']  

In [ ]:
#verilerin %45 ini teste sokucaz kalanını eğitime yollayacağız
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.45, random_state=101)

In [ ]:
model = SVC()
model.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
predictions = model.predict(X_test)
print(confusion_matrix(Y_test,predictions))

[[   0    0  701   20    0]
 [   0    0 2129   76    0]
 [   0    0 9338  312    0]
 [   0    0 5924  334    0]
 [   0    0 5232  207    0]]


In [ ]:
print(classification_report(Y_test,predictions))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

        Fair       0.00      0.00      0.00       721
        Good       0.00      0.00      0.00      2205
       Ideal       0.40      0.97      0.57      9650
     Premium       0.35      0.05      0.09      6258
   Very Good       0.00      0.00      0.00      5439

    accuracy                           0.40     24273
   macro avg       0.15      0.20      0.13     24273
weighted avg       0.25      0.40      0.25     24273



In [ ]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']}

In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [ ]:
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.401, total= 1.5min
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.5min remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.401, total= 1.5min
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  3.0min remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.401, total= 1.5min
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.401, total= 1.5min
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.401, total= 1.5min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.401, total= 1.2min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.401, total= 1.3min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.401, total= 1.3min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.401, total= 1.3min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] .

[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed: 226.6min finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [ ]:
grid.best_params_

{'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}

In [ ]:
grid.best_estimator_

SVC(C=1000, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(Y_test,grid_predictions))

[[ 199  189   78  133  122]
 [ 120  529  409  556  591]
 [  10  220 7841  715  864]
 [  44  363 1147 3434 1270]
 [  67  446 1755 1387 1784]]


In [ ]:
print(classification_report(Y_test,grid_predictions))

              precision    recall  f1-score   support

        Fair       0.45      0.28      0.34       721
        Good       0.30      0.24      0.27      2205
       Ideal       0.70      0.81      0.75      9650
     Premium       0.55      0.55      0.55      6258
   Very Good       0.39      0.33      0.35      5439

    accuracy                           0.57     24273
   macro avg       0.48      0.44      0.45     24273
weighted avg       0.55      0.57      0.55     24273

